-- Migration 003: Claim Atoms and Provenance
-- AlinaMatrix Enterprise — Enterprise Candidate — Active Development
-- Forward-only. Do not modify after deployment.

BEGIN;

-- ============================================================
-- CLAIMS
-- Atomic factual or inferred assertions extracted from evidence.
-- ============================================================
CREATE TABLE claims (
  id                      uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id               uuid        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  project_id              uuid        NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  -- SPO triple
  subject                 text        NOT NULL,
  predicate               text        NOT NULL,
  object                  text        NOT NULL,
  qualifier               text,
  time_scope              text,
  unit                    text,
  -- Display text (never authoritative; do not derive logic from this)
  claim_text              text        NOT NULL,
  -- Epistemics
  claim_type              text        NOT NULL
                                      CHECK (claim_type IN ('witnessed', 'inferred', 'assumption')),
  support_status          text        NOT NULL
                                      CHECK (support_status IN (
                                        'supported', 'weak', 'unsupported',
                                        'conflicting', 'not_applicable'
                                      )),
  -- Required when support_status is 'supported' or 'inferred'.
  -- Enforced at the application layer; DB stores the value or null.
  -- NULL is rejected by the application guard when status requires it.
  negative_evidence_note  text,
  -- Array of evidence_item UUIDs that ground this claim
  evidence_ids            uuid[]      NOT NULL DEFAULT '{}',
  -- 0.0 – 1.0 inclusive
  confidence              numeric(4,3)
                                      CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
  -- Contradiction tracking
  contradiction_status    text        NOT NULL DEFAULT 'none'
                                      CHECK (contradiction_status IN ('none', 'flagged', 'resolved')),
  -- Whether this claim was generated by an agent (false = human-authored fixture)
  generated               boolean     NOT NULL DEFAULT false,
  -- Human review status
  reviewer_status         text        NOT NULL DEFAULT 'pending'
                                      CHECK (reviewer_status IN ('pending', 'accepted', 'rejected')),
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- CITATIONS
-- A citation links an evidence item (and optionally a fragment)
-- to a claim, with a disposition status.
-- No DOI/PMID field: callers may not supply external identifiers.
-- ============================================================
CREATE TABLE citations (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       uuid        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  claim_id        uuid        NOT NULL REFERENCES claims(id) ON DELETE CASCADE,
  evidence_id     uuid        NOT NULL REFERENCES evidence_items(id) ON DELETE CASCADE,
  fragment_id     uuid        REFERENCES source_fragments(id) ON DELETE SET NULL,
  -- Disposition of this citation relative to the claim
  status          text        NOT NULL DEFAULT 'discovered'
                                        CHECK (status IN (
                                          'discovered', 'retrieved', 'parsed',
                                          'supports_claim', 'conflicts_with_claim', 'unverified'
                                        )),
  -- Verbatim quote from the fragment, if any.
  -- For 'witnessed' claims this MUST be an exact substring of fragment.text.
  quote           text,
  -- SHA-256 of quote — used by quote-lock validation.
  quote_hash      text,
  created_at      timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- ASSUMPTIONS
-- Explicit assumption records linked to a project (and optionally
-- to a specific claim). Distinct from claim_type='assumption' rows:
-- these are named, tracked, and reviewable standalone entries.
-- ============================================================
CREATE TABLE assumptions (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id    uuid        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  project_id   uuid        NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  claim_id     uuid        REFERENCES claims(id) ON DELETE SET NULL,
  statement    text        NOT NULL,
  rationale    text,
  reviewer_status text     NOT NULL DEFAULT 'pending'
                                    CHECK (reviewer_status IN ('pending', 'accepted', 'rejected')),
  created_at   timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- TERMINOLOGY ENTRIES
-- One canonical definition per term per project.
-- Uniqueness enforced by DB constraint.
-- ============================================================
CREATE TABLE terminology_entries (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id    uuid        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  project_id   uuid        NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  term         text        NOT NULL,
  definition   text        NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  -- One definition per term per project
  UNIQUE (project_id, term)
);

-- ============================================================
-- CLAIM EDGES
-- Provenance graph stored as edge rows.
-- No external graph database required.
-- edge_type values:
--   SUPPORTS        — source_claim_id supports target_claim_id
--   CONTRADICTS     — source_claim_id contradicts target_claim_id
--   DERIVED_FROM    — target_claim_id was derived from source_claim_id
-- ============================================================
CREATE TABLE claim_edges (
  id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id        uuid        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  source_claim_id  uuid        NOT NULL REFERENCES claims(id) ON DELETE CASCADE,
  target_claim_id  uuid        NOT NULL REFERENCES claims(id) ON DELETE CASCADE,
  edge_type        text        NOT NULL
                               CHECK (edge_type IN ('SUPPORTS', 'CONTRADICTS', 'DERIVED_FROM')),
  created_at       timestamptz NOT NULL DEFAULT now(),
  -- Prevent duplicate directed edges of the same type
  UNIQUE (source_claim_id, target_claim_id, edge_type)
);

-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX ON claims (tenant_id);
CREATE INDEX ON claims (project_id);
CREATE INDEX ON claims (claim_type);
CREATE INDEX ON claims (support_status);
CREATE INDEX ON citations (tenant_id);
CREATE INDEX ON citations (claim_id);
CREATE INDEX ON citations (evidence_id);
CREATE INDEX ON assumptions (tenant_id);
CREATE INDEX ON assumptions (project_id);
CREATE INDEX ON assumptions (claim_id);
CREATE INDEX ON terminology_entries (tenant_id);
CREATE INDEX ON terminology_entries (project_id);
CREATE INDEX ON claim_edges (tenant_id);
CREATE INDEX ON claim_edges (source_claim_id);
CREATE INDEX ON claim_edges (target_claim_id);

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================
ALTER TABLE claims              ENABLE ROW LEVEL SECURITY;
ALTER TABLE citations           ENABLE ROW LEVEL SECURITY;
ALTER TABLE assumptions         ENABLE ROW LEVEL SECURITY;
ALTER TABLE terminology_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE claim_edges         ENABLE ROW LEVEL SECURITY;

ALTER TABLE claims              FORCE ROW LEVEL SECURITY;
ALTER TABLE citations           FORCE ROW LEVEL SECURITY;
ALTER TABLE assumptions         FORCE ROW LEVEL SECURITY;
ALTER TABLE terminology_entries FORCE ROW LEVEL SECURITY;
ALTER TABLE claim_edges         FORCE ROW LEVEL SECURITY;

-- claims: tenant-scoped read and insert; reviewer_status update allowed
CREATE POLICY claims_select ON claims
  FOR SELECT
  USING (tenant_id = current_tenant_id());

CREATE POLICY claims_insert ON claims
  FOR INSERT
  WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY claims_update ON claims
  FOR UPDATE
  USING  (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());

-- citations: select and insert only (immutable after creation)
CREATE POLICY citations_select ON citations
  FOR SELECT
  USING (tenant_id = current_tenant_id());

CREATE POLICY citations_insert ON citations
  FOR INSERT
  WITH CHECK (tenant_id = current_tenant_id());

-- assumptions: select, insert, update reviewer_status
CREATE POLICY assumptions_select ON assumptions
  FOR SELECT
  USING (tenant_id = current_tenant_id());

CREATE POLICY assumptions_insert ON assumptions
  FOR INSERT
  WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY assumptions_update ON assumptions
  FOR UPDATE
  USING  (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());

-- terminology_entries: select, insert, update (definition may be corrected)
CREATE POLICY terminology_select ON terminology_entries
  FOR SELECT
  USING (tenant_id = current_tenant_id());

CREATE POLICY terminology_insert ON terminology_entries
  FOR INSERT
  WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY terminology_update ON terminology_entries
  FOR UPDATE
  USING  (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());

-- claim_edges: select and insert only
CREATE POLICY claim_edges_select ON claim_edges
  FOR SELECT
  USING (tenant_id = current_tenant_id());

CREATE POLICY claim_edges_insert ON claim_edges
  FOR INSERT
  WITH CHECK (tenant_id = current_tenant_id());

-- ============================================================
-- GRANTS
-- app_user is the connection role for all application queries.
-- Table-level grants are required; RLS policies then filter rows.
-- ============================================================
GRANT SELECT, INSERT, UPDATE, DELETE ON claims              TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON citations           TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON assumptions         TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON terminology_entries TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON claim_edges         TO app_user;

-- ============================================================
-- MIGRATION REGISTRY
-- ============================================================
INSERT INTO schema_migrations (name) VALUES ('003_claims_provenance');

COMMIT;
